version: '3'
services:
    server:
        build: .
        ports:
            - "8000:8000"
        network_mode: "host"
        restart: always
    database:
        image: mongo:latest
        ports:
            - "27017:27017"
        environment:
            MONGODB_DATABASE: "venturerealm"
        network_mode: "host"
        restart: always
